platform :ios,'9.0'
target 'Chat' do
	pod 'Bolts'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'Firebase'
	pod 'Parse'
	pod 'ParseFacebookUtilsV4'
	pod 'ParseTwitterUtils'

	pod 'AFNetworking', '~> 2.6.3'
	pod 'IQAudioRecorderController'
	pod 'MBProgressHUD'
	pod 'ProgressHUD'
	pod 'RNGridMenu'
	pod 'SDWebImage'
end